name: Flutter CI

on:
  push:
    branches: [ main ]

env:
  FLUTTER_VERSION: '3.35.2'

jobs:
  analyze:
    name: Analyze code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

  build_android:
    name: Build android app
    runs-on: ubuntu-latest
    needs: analyze
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Install dependencies
        run: flutter pub get

      - name: Decode keystore
        run: echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks

      - name: Create key.properties
        run: |
          cat > android/key.properties <<EOF
          storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}
          keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}
          storeFile=upload-keystore.jks
          EOF

      - name: Build android APK
        run: flutter build apk --release --build-number=${{ github.run_number }}

      - name: Upload android artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android_build
          path: build/app/outputs/flutter-apk/app-release.apk


  build_windows:
      name: Build windows app
      runs-on: windows-latest
      needs: analyze
      steps:
        - name: Checkout code
          uses: actions/checkout@v5

        - name: Setup flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version: ${{ env.FLUTTER_VERSION }}

        - name: Install dependencies
          run: flutter pub get

        - name: Build windows EXE
          run: flutter build windows --release --build-number=${{ github.run_number }}

        - name: Zip windows build folder
          run: |
            cd build/windows/x64/runner/Release
            powershell Compress-Archive * ../../../../../windows_build.zip

        - name: Upload windows build artifacts
          uses: actions/upload-artifact@v4
          with:
            name: windows_build
            path: windows_build.zip

  release:
      name: Create release
      runs-on: ubuntu-latest
      needs: [build_android, build_windows]
      steps:
        - name: Checkout code
          uses: actions/checkout@v5

        - name: Get version from pubspec.yaml
          id: get_version
          shell: bash
          run: |
            VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: //g' | cut -d+ -f1)
            echo "version=$VERSION" >> $GITHUB_OUTPUT

        - name: Download android build artifacts
          uses: actions/download-artifact@v4
          with:
            name: android_build
            path: artifacts/android

        - name: Download windows build artifacts    
          uses: actions/download-artifact@v4
          with:
            name: windows_build
            path: artifacts/windows

        - name: Upload artifacts to Release
          uses: softprops/action-gh-release@v2
          with:
            tag_name: v${{ steps.get_version.outputs.version }}+${{ github.run_number }}
            name: "Release v${{ steps.get_version.outputs.version }}+${{ github.run_number }}"
            draft: false
            prerelease: false
            files: |
              artifacts/android/app-release.apk
              artifacts/windows/windows_build.zip
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}